### ISSUE TITLE
First Look

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#1]
## Value Proposition

**As a** User  
**I want to** I want to see a list of all posted Pictures  
**so that** I can scroll through the list and get an overview 
​

## Description

​
<img width="200" alt="Bildschirm­foto 2023-01-19 um 13 56 27" src="https://user-images.githubusercontent.com/118187307/213448534-b0d3321d-2d0d-43b6-be9f-0ccb935b07f8.png">

## Acceptance Criteria

- [ ] All card objects are displayed as a list from an array
- [ ] In a card, the name of the photographer is displayed
- [ ] In a card, the profile picture of the photographer is displayed
- [ ] In a card, the main picture of the photographer is displayed
- [ ] In a card, the description of the picture is displayed
- [ ] In a card, the date of posting the picture is displayed
- [ ] In a card, the categories of the picture are displayed
      ​

## Tasks

- [ ] create an Array of Objects. Each Object has information about the photographer and the picture
- [ ] create a component that displays a list, each list item is a component that displays one object
      ​

## Complexity

S

**Comment by d-opri** [comment]
with main picture do you mean the backround images? if so, you have a profile icon with name and like button displayed but not mentioned in your acceptance criteria. you can take those out and implement them later on :)
