### ISSUE TITLE
image upload

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#11]
## Value Proposition

**As a** User
**I want to** upload my own pictures 
**so that** I get a repertoire of my own pictures
​

## Description
​
<img width="400" alt="Bildschirm­foto 2023-01-26 um 11 07 47" src="https://user-images.githubusercontent.com/118187307/214809531-d502593e-9cb1-4ea1-8c3e-d38c196923cb.png">

## Acceptance Criteria

- [ ] input field for files is displayed
- [ ] user can choose a file from his device
      ​

## Tasks

- [ ] create a cloudinary account
- [ ] add a api folder to the pages folder and add a upload.js file
- [ ] install and import `formidable` and `cloudinary` to the upload.js
- [ ] create `.env.local` and add the keys from cloudinary
- [ ] write a handler function in the upload.js that sends the uploaded file to cloudinary and sends the new url back to your frontend
- [ ] go to the `UploadForm` and change the type of image url input to type `file`
- [ ] change the `handleSubmit`function and send the file to your api 
- [ ] use now the given url from cloudinary for the picture object
      ​

## Complexity

M

**Comment by JoergWolff** [comment]
Hello Niklas, just seen and already in the us. LGTM
