### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#12]
## Value Proposition

**As a** User
**I want to** I want to have a profile page
**so that** I can see my profile and my uploads  
​

## Description
​
the option to see liked pictures is coming in further user stories
<img width="250" alt="Bildschirm­foto 2023-01-26 um 11 36 33" src="https://user-images.githubusercontent.com/118187307/214815348-8e2e4937-6a47-4e51-b85b-26576bd05343.png">

## Acceptance Criteria

- [ ] The Profile Image is displayed
- [ ] The User Name is displayed
- [ ] The User Description is displayed
- [ ] A counter of uploads is displayed
- [ ] The year of registration is displayed
- [ ] a list of all user uploads is displayed
      ​

## Tasks

- [ ] add a profile.js to the pages folder
- [ ] create a component that renders the profile information from above
- [ ] create a component that renders the user uploads
- [ ] add both components to the profile.js
      ​

## Complexity

S

**Comment by minatimar** [comment]
lgtm - happy hacking
