### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#13]
## Value Proposition

**As a** ... (User, Author, logged in User...)  
**I want to** ... (describe the goal)  
**so that** ... (describe the reason)  
​

## Description

... (Wireframe, scribble, design or text)
​

## Acceptance Criteria

- [ ] Describe every scenarios in detail
- [ ] e.g. Aall inputs are required, show warning if empty.
- [ ] ...
      ​

## Tasks

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] ...
      ​

## Complexity

... (T-Shirt Sizes XS to XL)

**Comment by JohannesMisch** [comment]
Hey, your story looks really good. 👍

**Comment by AGeck113** [comment]
Looks fine, I have nothing else to mention here 😄
