### ISSUE TITLE
Like Function

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#14]
## Value Proposition

**As a** User 
**I want to** like pictures 
**so that** I can save pictures and browse through them later on
​

## Description
​
<img width="300" alt="Bildschirm­foto 2023-01-26 um 13 52 32" src="https://user-images.githubusercontent.com/118187307/214840181-f9a9eab3-564e-4d6e-a8db-9e544e8c9984.png">

## Acceptance Criteria

- [x] a heart icon is displayed at each list item on the overview page
- [x] a heart icon is displayed on the details page
- [x] on the profile page is a tab bar navigation for switching between uploads and liked pictures
- [x] the tab 'liked pictures' displays all liked pictures
      ​

## Tasks

- [x] create a button component including the heart icon
- [x] the button gets a `handleLike` function
- [x] write a `handleLike` function that adds or removes the post id from the users `likedPosts`
- [x] add the button component to the ListItem and PictureDetails component
- [x] create a tab bar navigation to the profile page that makes conditional rendering between uploads and liked pictures
      ​

## Complexity

L

**Comment by AstridOttmann** [comment]
Nice!
