### ISSUE TITLE
Create Database

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#15]
## Value Proposition

**As a** User 
**I want to** save pictures  
**so that** I still have my pictures after refreshing or changing the browser
​

## Description

All in all, I want to create a Mongo DB Atlas and fetch from and to it
​

## Acceptance Criteria

- [ ] All pictures that are displayed anywhere are from the database
- [ ] The upload form sends the new picture to the database
      ​

## Tasks

- [ ] Create a database on MongoDB Atlas
- [ ] Prepare the database connection
- [ ] Create a database function to `find` all pictures
- [ ] Create an api endpoint in your `api/pictures` route for fetching all places from the database
- [ ] Fetch now everywhere where you used `initialPictures` and use the fetched pictures
- [ ] Create a database function to `post` a new picture
- [ ] Fetch now in the `handleSubmit` function in the upload.js file and sent the picture to the DB
      ​

## Complexity

XL
