### ISSUE TITLE
Details Page

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#2]
## Value Proposition

**As a** User 
**I want to** click on single list items and get to a details page
**so that** I can get more information about the picture
​

## Description

<img width="200" alt="Bildschirm­foto 2023-01-19 um 14 41 18" src="https://user-images.githubusercontent.com/118187307/213457534-07f472f7-550c-47d6-b03f-e4acb112a109.png">
e, design or text)
​

## Acceptance Criteria

- [ ] If a card is clicked, the user will see a details page
- [ ] The picture details page displays the name of the photographer
- [ ] The picture details page displays the profilpicture of the photographer
- [ ] The picture details page displays the description of the picture
- [ ] The picture details page displays the categories of the picture
- [ ] The picture details page displays the settings like Film, Aperture, Time, Objektiv, Camera of the picture
- [ ] The picture details page displays the picture itself
- [ ] The picture details page displays the date of uploading the picture
      ​

## Tasks

- [ ] add a link to each list item, that links to the details page
- [ ] add dynamic routing and create a details page that displays all Acceptance Criteria
      ​

## Complexity

XS
