### ISSUE TITLE
Structure Data

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#21]
## Value Proposition

**As a** Developer
**I want to** have the best data structure 
**so that** I can handle easily all my use cases.
​

## Description

In this Userstory I wanna find the best structure for my data.
​

## Acceptance Criteria

- [ ] having a user array
- [ ] having a posts array
- [ ] having a comments array
      ​

## Tasks

- [ ] create a globalstate for `posts`, `comments` and `user` like the following [example](https://redux.js.org/usage/structuring-reducers/normalizing-state-shape)
- [ ] add some initial objects to the new states
- [ ] use this arrays and implement them in the actual code so that every thing is still working like before but with the new data structure
- [ ] add a localStorageState to save which user is logged in
- [ ] make the profile page dynamic according to what user is logged in​

## Complexity

L
