### ISSUE TITLE
Delete Post

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#24]
## Value Proposition

**As a** User
**I want to** delete my own pictures
**so that** I that I can delete pictures I don't like anymore
​

## Description

​

## Acceptance Criteria

- [ ] display a delete button on the post details page
- [ ] display the button only if it's the picture of the logged-in user
- [ ] a popup window will be shown after clicking delete if you really wanna delte the post
      ​

## Tasks

- [ ] add a button to the post details page
- [ ] write a function and an api route for deleting a post from the database
- [ ] make sure only the logged-in user can delete their own posts by displaying the delete buttons only on their posts
- [ ] create a popup window that pops up after clicking the delete button
- [ ] the popup window should ask if you really wanna delete the post
- [ ] only when clicking on the new button "yes I'm sure" call the delete function 
      ​

## Complexity

S

**Comment by RobinWitt** [comment]
looks good to me

**Comment by RobinWitt** [comment]
maybe you can add a description?
