### ISSUE TITLE
Creater User

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#25]
## Value Proposition

**As a** User
**I want to** create my own account 
**so that** I can post my own data
​

## Description
​
<img width="853" alt="Bildschirm­foto 2023-02-06 um 17 58 48" src="https://user-images.githubusercontent.com/118187307/217035379-78e25ddd-197b-4829-8932-083f02cd7c10.png">

## Acceptance Criteria

- [ ] display a settings icon
- [ ] display popup by clicking on settings icon
- [ ] display create icon with text "Create new profile"
- [ ] display a form  with input for uploading image, write a bio and a user name
- [ ] display a submit button
      ​

## Tasks

- [ ] add a component `userSetting`
- [ ] add the settings icon to the component und use a use State for showing the Popup window
- [ ] add the create profile icon and text to the popup as a button
- [ ] add the component to the profile page
- [ ] create a page for creating a new user that renders a form with input for image upload, bio and name and a submit button
- [ ] create a function that adds the new user to the database an logs the user in
      ​

## Complexity

... (T-Shirt Sizes XS to XL)

**Comment by Long-HaHoang** [comment]
Hi Niklas,
Good story and the complexity depends on you.

There is just one typo in your last task.

> database an logs

`an` → `and`

Besides that it's ok. 👍
