### ISSUE TITLE
Edit Profile

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#26]
## Value Proposition

**As a** User
**I want to** edit my profile
**so that** I can change my informations about me
​

## Description

<img width="350" alt="Bildschirm­foto 2023-02-06 um 18 15 41" src="https://user-images.githubusercontent.com/118187307/217039236-bffdbdf0-8767-4144-af69-42534bac0999.png">

## Acceptance Criteria

- [ ] display edit icon with text "Edit profile" in that popup window
- [ ] display a form with input for uploading image, edit the bio and the user name
- [ ] display a submit button
      ​

## Tasks

- [ ] add the edit profile icon and text to the popup as a button
- [ ] ​edit the create profile page/form so that you have the same form but using for edit or creating
- [ ] write a function that updates the user object and pass it to the form

## Complexity

M

**Comment by HosseinKrouna** [comment]
Hello Niklas, looks pretty good so far. 
I'm not entirely sure if you accidentally tried to show a different wireframe? I understand e.g. not where the form is for the new profile and the inputs with the submit button.

But you can also enlighten me 😆, then I can give you the nicer checkmark

**Comment by niklasrammelkamp** [comment]
Hi @HosseinKrouna, thanks. 
I know, I don't have a wireframe or design for that.

**Comment by HosseinKrouna** [comment]
Hi,
I don't know, my review was rejected because the description was missing. I think that's part of the process, or isn't it?

**Comment by niklasrammelkamp** [comment]
I only write a description when I don't have a wireframe. I think that's not necessary

**Comment by HosseinKrouna** [comment]
well then feel free 👍
