### ISSUE TITLE
Dynamic User Pages

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#27]
## Value Proposition

**As a** User 
**I want to** visit other user pages
**so that** I have an overview what other users are posting and liking
​

## Description

​
<img width="300" alt="Bildschirm­foto 2023-02-06 um 18 38 09" src="https://user-images.githubusercontent.com/118187307/217044355-fbf652a1-8b0e-44bc-8cd9-8337e53f15c5.png">

## Acceptance Criteria

- [ ] display the same user information as on the logged-in user page without the settings icon
      ​

## Tasks

- [ ] create a dynamic route for user pages `pages/users/[id].js`
- [ ] add the same components to the page as on the logged-in user page without the settings icon ​
- [ ] create links everywhere you have information about who uploaded a post or wrote a comment

## Complexity

S

**Comment by Long-HaHoang** [comment]
Overall nice story.
Just one thing the `N icon` position in your description image seems off to me.
Is it part of the `liked pictures`?
