### ISSUE TITLE
Loading Screen

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#28]
## Value Proposition

**As a** User
**I want to** see when something is loading
**so that** I have a better feeling about what is happening.
​

## Description

The User wants to see a better loading screen if data is loading
​

## Acceptance Criteria

- [ ] display an animated svg with an optional text like "is loading" 
      ​

## Tasks

- [ ] create a component that renders an animated svg 
- [ ] return the component everywhere where you use the `isLoading`state from swr is using 
      ​

## Complexity

XS

**Comment by HosseinKrouna** [comment]
Hi Niklas,
reads very conclusively...lgtm 👍
