### ISSUE TITLE
Filter Overview Page

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#3]
## Value Proposition

**As a** User
**I want to** filter the overview page  
**so that** I only get displayed what I'm interested in
​

## Description

​
<img width="200" alt="Bildschirm­foto 2023-01-19 um 15 15 30" src="https://user-images.githubusercontent.com/118187307/213465054-a2814be1-f826-4423-bf50-c9c1f2d2bad7.png">

## Acceptance Criteria

- [ ] The overview page displays a list of filters
      ​

## Tasks

- [ ] Add filter criteria to the overview page
- [ ] each filter is a button I can toggle
- [ ] change the list, so that I only get displayed the items with the filtered categories
      ​

## Complexity

M

**Comment by ThomasF85** [comment]
Nice, small story!

However, your acceptance criteria should contain the relevant description (or possible test cases) of the new feature. I am missing the very important functionality that the list actually gets filtered once I click a filter. Also I don't know if I can apply multiple filters at the same time / what happens if I click on multiple filters. Please add these specifications in the form of acceptance criteria.

**Comment by NikRoe** [comment]
looks very nice after applying Thomas' suggestions 👍
