### ISSUE TITLE
Styling: LogIn Screen

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#35]
## Value Proposition

**As a** User
**I want to** have a better UI
**so that** it's easier to understand the app.
​

## Description

​

## Acceptance Criteria

- [ ] display app logo
- [ ] display headline 
- [ ] display login button for GitHub
      ​

## Tasks

- [ ] add the app logo to the LogIn component
- [ ] add styling to the Login button
- [ ] add styling to the headline
      ​

## Complexity

XS

**Comment by Long-HaHoang** [comment]
Simple enough.
