### ISSUE TITLE
Styling: Feed Page

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#36]
## Value Proposition

**As a** User
**I want to** have a better UI
**so that** it's easier to understand the app.
​

## Description

​
<img width="400" alt="Bildschirm­foto 2023-02-10 um 11 20 34" src="https://user-images.githubusercontent.com/118187307/218067270-e9df8a36-226b-4587-b4ff-7260bbc6658f.png">

## Acceptance Criteria

- [ ] display styled filter
- [ ] display styled posts
      ​

## Tasks

- [ ] add styling to the filter component
- [ ] add styling to the feed list and the single posts
      ​

## Complexity

S

**Comment by Long-HaHoang** [comment]
I like your blur effect.
