### ISSUE TITLE
Adjust Upload Form

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#37]
## Value Proposition

**As a** User
**I want to** have a better UI at the upload form
**so that** I have a better understanding about what options I have.
​

## Description
​
<img width="363" alt="Bildschirm­foto 2023-02-10 um 13 00 24" src="https://user-images.githubusercontent.com/118187307/218087482-121f777f-d874-4b1e-bb83-c569623efc29.png">

## Acceptance Criteria

- [ ] display styled input fields
- [ ] the settings are optional
- [ ] you can select max 3 categories
- [ ] display styled submit button
- [ ] display loading screen while uploading
- [ ] you can only upload pictures with max 3 MB
      ​

## Tasks

- [ ] create styling for input fields and buttons
- [ ] create logic that you only can upload pictuers with a max size of 3 MB
- [ ] create a loading screen while uploading
- [ ] create logic that you only can select 3 categories
- [ ] adjust the search function using "includes the serachinput" instead of "starts with searchinput"

      ​

## Complexity

M

**Comment by RobinWitt** [comment]
looks nice
