### ISSUE TITLE
Upload Form

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#4]
## Value Proposition

**As a** User
**I want to** upload pictures
**so that** I can upload pictures and store my uploads
​

## Description

<img width="200" alt="Bildschirm­foto 2023-01-20 um 11 12 52" src="https://user-images.githubusercontent.com/118187307/213670663-9ac94279-24c5-465d-9a7d-bf4acf6447fa.png">

​

## Acceptance Criteria

- [ ] A description input is displayed
- [ ] A category-select field is displayed
- [ ] You can add more category-select fields for choosing more categories, using an add button
- [ ] You can remove category-select fields, using a remove button
- [ ] You have to choose at least one category
- [ ] A Film input is displayed
- [ ] A Aperture input is displayed
- [ ] A Time input is displayed
- [ ] A Objektiv input is displayed
- [ ] A Camera input is displayed
- [ ] A Submit button is displayed
- [ ] By clicking the submit button a new object gets created and pushed to the Pictures Array. You also get navigated to the main page (overview page)

## Side Fact
You can't upload any images now because we haven't had the workshop for user uploads.
      ​

## Tasks

- [ ] Create a form component rendering all input fields and the submit button inside a form element, which is expecting an "onSubmit" prop
- [ ] find a solution for adding and removing category-select fields
- [ ] Add the "onSubmit" prop as the callback function for the submit event of the form
- [ ] Add a upload.js to the pages folder for the upload page
- [ ] Create a page component in this file that uses the form component for rendering the input fields
- [ ] Write a handleSubmit function that expects a submit event object
- [ ] Inside this function, you create a new pictures object and return it
- [ ] On the upload page write a function that adds a new object to the pictures array and navigates to the overview page
      ​

## Complexity

L

**Comment by doemser** [comment]
Your user story is a bit redundant and justifies itself with itself. "I want to eat to have eaten." 

This could be more of a fit:
As a user, I want to upload pictures so that I can store and access them at a later time.

I would say that the complexity with L is greatly underestimated, my first impression is that this user-story contains at least 4 user-stories. 
Try to shorten this user-story drastically and create in a first iteration the form and its function, completely independent from an image upload. Also consider if the form might not even be split into two user-stories.

**Comment by niklasrammelkamp** [comment]
Hi Dominik, I changed my User Story, you were right.

The last two sentences I don't really understand 'cause In the whole user story I wanna add a form and its function like you said. In this story, I can't upload any images because I think it's a bit more difficult and we haven't had the workshop for that.

**Comment by doemser** [comment]
Maybe I got a little confused, the main purpose of your app is photographs, I just didn't have that in mind. Okay, then go for it, but try to describe even better how you want to fake the upload for now.  I can't find enough info about that just yet.

**Comment by doemser** [comment]
My concern still exists, here are a few sample AC's and tasks for an actual image upload:

Acceptance Criteria:

- The user is able to select an image file from their device
- The image file is successfully uploaded to the server
- The user is able to view and access the uploaded image at a later time
- 
Tasks:

- Implement file selection feature on the front-end using a file input element
- Handle the file upload process on the back-end using a server-side language (e.g. Node.js, Python, etc.)
- Store the uploaded image on a file system or cloud storage service (e.g. AWS S3, Google Cloud Storage, etc.)

So: How do you want to fake the upload?

**Comment by AstridOttmann** [comment]
Looks good now!
