### ISSUE TITLE
Styling: Profile Page

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#41]
## Value Proposition

**As a** User
**I want to** have a better UI
**so that** it's easier to understand the app.
​

## Description

<img width="310" alt="Bildschirm­foto 2023-02-13 um 13 05 34" src="https://user-images.githubusercontent.com/118187307/218453435-6918b034-7cbd-49a0-8101-80614a9f34ae.png">

​

## Acceptance Criteria

- [ ] display styled profile informations
- [ ] display styled list of posts
      ​

## Tasks

- [ ] add styling to the profile informations
- [ ] add styling to the list of posts
      ​

## Complexity

S
