### ISSUE TITLE
comment function

### ISSUE THREAD

**Issue by niklasrammelkamp** [niklasrammelkamp/capstone-project#5]
## Value Proposition

**As a** User
**I want to** comment all pictures
**so that** I can tell other users what I think about the picture
​

## Description

In this case, the information about the user won't be shown. This gets implemented later.

<img width="200" alt="Bildschirm­foto 2023-01-20 um 17 16 43" src="https://user-images.githubusercontent.com/118187307/213749215-7235731d-b578-4e74-9624-baba4d76da66.png">

## Acceptance Criteria

- [ ] A comment input field is displayed
- [ ] A add button is displayed
- [ ] The comments are displayed as list
- [ ] If there is no comment, a text like "no comments yet" is displayed
- [ ] A delete button for each comment is displayed
      ​

## Tasks

- [ ] Write a form component that renders an input field and a submit button
- [ ] Write an onSubmit event that adds the comment from the input to an array which will add to the pictures-object
- [ ] write a component that renders the list of comments
- [ ] Add the two components to the Detailspage 
      ​

## Complexity

M

**Comment by JoergWolff** [comment]
Hi there, nice work.
LGTM
